language: dart
dart:
# Install the latest stable release
- stable

dart_task:

# As long as you don't want any other configuration, you can just use the name
# of a task instead of "name: true".
- test
#- dartanalyzer: --fatal-warnings --fatal-infos lib
#- dartfmt


services:
- mysql
